= KAPI Specification
:revnumber: 0.4
:author: Elizabeth Paige Harper
:toc: macro
:toclevels: 4
:toc-title:

== Active Notes

unorganized development notes for this rough draft.

=== Table of Contents
toc::[]

=== Inline Type References

.Examples
* `any`
* `any?`
* `boolean`
* `boolean?`
* `date`
* `date?`
* `decimal`
* `decimal?`
* `integer`
* `integer?`
* `object`
* `object?`
* `string`
* `string?`

collection and map types must follow one of these patterns:

.Examples
* `array[boolean]`
* `array[date?]`
* `array[decimal]?`
* `array[integer?]?`
* `list[boolean]`
* `list[date?]`
* `list[decimal]?`
* `list[integer?]?`
* `map[string, boolean]`
* `map[integer, date?]`
* `map[MyType, decimal]?`
* `map[string, integer?]?`
* `set[boolean]`
* `set[date?]`
* `set[decimal]?`
* `set[integer?]?`


== Types

=== Builtin Types

* array
* boolean
* date
* decimal
* enum
* integer
* list
* map
* object
* set
* string


=== Using Types

==== Shorthand

==== Longform

=== Defining Custom Types

==== Enums

===== Plain Enum

A plain enum is an enum that does not wrap any internal values.  The name of the
enum values _is_ the serialized form.

.Type Definition
[source, yaml]
----
MyPlainEnum:
  type: enum
  wraps: none
  values:
  - EnumValue1
  - EnumValue2
----

.Serialized
[source, json]
----
"EnumValue1"
----

===== Boolean Enum

===== Decimal Enum

===== Integer Enum

===== String Enum

.Type Definition
[source, yaml]
----
MyStringEnum:
  type: enum
  wraps: string
  values:
    Value1: value-1
    Value2: value-2
----

.Serialized
[source, json]
----
"value-1"
----

==== Objects

[source, yaml]
----
MyObjectType:
  type: object
  typeHintField: kind
  properties:
    kind: types.MyObjectKind
    name: string
    date:
      type: date
      format: datetime
    nullableField: integer?
----

[source, yaml]
----
MySubObjectType:
  type: object
  extends: types.MyObjectType
  typeHintValue: Kind1
  properties:
    mapField:
      summary: Map of strings
      type: map[string, string]
    listField:
      summary: List of nullable string values
      type: list[string?]
    setField:
      summary: Nullable set of non-nullable string values
      type: set[string]?
    arrayField:
      summary: Nullable array of nullable string values
      type: array[string?]?
----

