= KAPI Specification
:revnumber: 0.4
:author: Elizabeth Paige Harper
:toc: macro
:toc-title:

== Active Notes

unorganized development notes for this rough draft.

=== Inline Type References

simple and custom type names will be just the type name followed by an optional
`?` character to indicate nullability.

.Examples
* `boolean`
* `boolean?`
* `date`
* `date?`
* `decimal`
* `decimal?`
* `integer`
* `integer?`
* `string`
* `string?`

collection and map types must follow one of these patterns:

* array: `+^array\[(\w[\w\d]*\??)\]\??$+`
* list: `+^list\[(\w[\w\d]*\??)\]\??$+`
* map: `+^map\[(\w[\w\d]*), ?(\w[\w\d]*\??)\]\??$+`
* set: `+^set\[(\w[\w\d]*\??)\]\??$+`

.Examples
* `array[boolean]`
* `array[date?]`
* `array[decimal]?`
* `array[integer?]?`
* `list[boolean]`
* `list[date?]`
* `list[decimal]?`
* `list[integer?]?`
* `map[string, boolean]`
* `map[integer, date?]`
* `map[MyType, decimal]?`
* `map[string, integer?]?`
* `set[boolean]`
* `set[date?]`
* `set[decimal]?`
* `set[integer?]?`


== Types

=== Builtin Types

* array
* boolean
* date
* decimal
* enum
* integer
* list
* map
* object
* set
* string


=== Using Types

==== Shorthand

==== Longform

=== Defining Custom Types

==== Enums

[source, yaml]
----
MyObjectKind:
  wraps: string
  values:
    Kind1: kind-1
    Kind2: kind-2
----

==== Objects

[source, yaml]
----
MyObjectType:
  type: object
  typeHintField: kind
  properties:
    kind: types.MyObjectKind
    name: string
    date:
      type: date
      format: datetime
    nullableField: integer?
----

[source, yaml]
----
MySubObjectType:
  type: object
  extends: types.MyObjectType
  typeHintValue: Kind1
  properties:
    mapField:
      summary: Map of strings
      type: map[string, string]
    listField:
      summary: List of nullable string values
      type: list[string?]
    setField:
      summary: Nullable set of non-nullable string values
      type: set[string]?
    arrayField:
      summary: Nullable array of nullable string values
      type: array[string?]?
----

