= KAPI Specification
:revnumber: 0.4
:author: Elizabeth Paige Harper
:toc: preamble
:toclevels: 4
:toc-title:
:icons: font

*Version: {revnumber}*

KAPI is a YAML or JSON based syntax for defining HTTP-based REST APIs.

== Terms & Definitions

This specification uses the terms/keywords "MUST", "MUST NOT", "SHOULD", "SHOULD NOT", "MAY", and "OPTIONAL".  These
terms are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[BCP-14]
(https://datatracker.ietf.org/doc/html/rfc2119[RFC2119] and https://datatracker.ietf.org/doc/html/rfc8174[RFC8174])
when, and only when, they appear in all capital letters as shown in this paragraph.

=== Definitions

KAPI Specification::
Refers to this document.

KAPI Document::
A YAML or JSON document that is, by design, valid against the link:kapi-spec.yml[KAPI JSON Schema Definition].  This
document MUST contain the defined required keywords, and be one of either an <<API Definition>> or
<<Library Definition>>.

Template URI::
+
WARNING: TODO: replace all references to "pattern uri" with "template uri" in the JSON schema document.


== Active Notes

unorganized development notes for this rough draft.

=== Inline Type References

.Examples
* `any`
* `any?`
* `boolean`
* `boolean?`
* `date`
* `date?`
* `decimal`
* `decimal?`
* `integer`
* `integer?`
* `object`
* `object?`
* `string`
* `string?`

collection and map types must follow one of these patterns:

.Examples
* `array[boolean]`
* `array[date?]`
* `array[decimal]?`
* `array[integer?]?`
* `list[boolean]`
* `list[date?]`
* `list[decimal]?`
* `list[integer?]?`
* `map[string, boolean]`
* `map[integer, date?]`
* `map[MyType, decimal]?`
* `map[string, integer?]?`
* `set[boolean]`
* `set[date?]`
* `set[decimal]?`
* `set[integer?]?`


== Types

=== Builtin Types

* array
* boolean
* date
* decimal
* integer
* list
* map
* object
* set
* string

.Common Properties
[cols="2m,1m,7"]
|===
| Property | Required | Description

| summary
| false
| Short summary of the type being referenced or defined.

| description
| false
| Long description or help text of the type being referenced or defined and its
  usage.

| example
| false
| A single example value of the type being referenced or defined.

| examples
| false
| Array of described example values of the type being referenced or defined.
|===

==== Array

===== Reference

Shorthand::
* `array[MyType]`
* `array[MyType?]`
* `array[MyType]?`
* `array[MyType?]?`

Longform::
+
[source, yaml]
----
type: array
values:
  type: types.MyType
  nullable: true
----

===== Definition

==== Boolean

===== Reference

Shorthand::
* `boolean`
* `boolean?`

Longform::
+
[source, yaml]
----
type: boolean
example: true

----

==== Date

Shorthand::
* `date`
* `date?`

==== Decimal

Shorthand::
* `decimal`
* `decimal?`

==== Integer

Shorthand::
* `integer`
* `integer?`

==== List

Shorthand::
* `list[MyType]`
* `list[MyType?]`
* `list[MyType]?`
* `list[MyType?]?`

==== Map
==== Object
==== Set
==== String


=== Using Types

==== Shorthand

==== Longform

=== Defining Custom Types

==== Enums

===== Plain Enum

A plain enum is an enum that does not wrap any internal values.  The name of the
enum values _is_ the serialized form.

.Type Definition
[source, yaml]
----
MyPlainEnum:
  type: enum
  wraps: none
  values:
  - EnumValue1
  - EnumValue2
----

.Serialized
[source, json]
----
"EnumValue1"
----

===== Boolean Enum

===== Decimal Enum

===== Integer Enum

===== String Enum

.Type Definition
[source, yaml]
----
MyStringEnum:
  type: enum
  wraps: string
  values:
    Value1: value-1
    Value2: value-2
----

.Serialized
[source, json]
----
"value-1"
----

==== Objects

[source, yaml]
----
MyObjectType:
  type: object
  typeHintField: kind
  properties:
    kind: types.MyObjectKind
    name: string
    date:
      type: date
      format: datetime
    nullableField: integer?
----

[source, yaml]
----
MySubObjectType:
  type: object
  extends: types.MyObjectType
  typeHintValue: Kind1
  properties:
    mapField:
      summary: Map of strings
      type: map[string, string]
    listField:
      summary: List of nullable string values
      type: list[string?]
    setField:
      summary: Nullable set of non-nullable string values
      type: set[string]?
    arrayField:
      summary: Nullable array of nullable string values
      type: array[string?]?
----

